// Foydalanish shartlari va Maxfiylik siyosati (uz / ru / en).
// Eslatma: bu matn loyiha jamoasi uchun tayyorlangan qoralama; rasmiy e'lon qilishdan oldin yurist ko'rib chiqishi tavsiya etiladi.
import { CONTACT, OPERATOR } from '@/lib/site';

const MAILTO = CONTACT.email ? ` Elektron pochta: ${CONTACT.email}.` : '';
const MAILTO_RU = CONTACT.email ? ` Электронная почта: ${CONTACT.email}.` : '';
const MAILTO_EN = CONTACT.email ? ` Email: ${CONTACT.email}.` : '';
export const UPDATED = '2026-10-02';

export const TERMS = {
  uz: [
    { h: '1. Umumiy qoidalar', p: ["Investage (bundan keyin — «Platforma») startaplar va investorlarni bir-biri bilan tanishtiruvchi onlayn xizmatdir. Platformadan foydalanish yoki unda ro'yxatdan o'tish orqali siz ushbu shartlarga rozilik bildirasiz.", "Agar shartlarga rozi bo'lmasangiz, Platformadan foydalanmang."] },
    { h: "2. Hisob va ro'yxatdan o'tish", p: ["Ro'yxatdan o'tishda to'g'ri va dolzarb ma'lumot kiritishingiz kerak. Platformadan 18 yoshga to'lgan shaxslar foydalanishi mumkin.", "Har bir hisob bitta rolga ega: startap yoki investor. Hisobingiz va parolingiz xavfsizligi uchun o'zingiz javobgarsiz."] },
    { h: '3. Platforma nima qiladi va nima qilmaydi', p: ["Platforma startaplarga o'zini tanishtirish, investorlarga esa ularni topish va yopiq ma'lumotga kirish so'rovini yuborish imkonini beradi. Yopiq ma'lumot faqat startap ruxsat bergan investorga ochiladi.", "Investage moliyaviy vositachi, broker yoki investitsiya maslahatchisi emas. Platforma to'lovlarni qabul qilmaydi va pul o'tkazmaydi: barcha kelishuv va hisob-kitoblar startap va investor o'rtasida bevosita amalga oshiriladi.", "Investage bahosi va «Tasdiqlangan» belgisi investitsiya tavsiyasi yoki kafolat emas. Ular faqat qo'shimcha ma'lumot sifatida beriladi."] },
    { h: '4. Foydalanuvchining majburiyatlari', p: ['Quyidagilar taqiqlanadi:'], list: ["yolg'on yoki chalg'ituvchi ma'lumot joylashtirish;", "firibgarlik, spam yoki boshqa foydalanuvchilarni bezovta qilish;", "sizga ochilgan yopiq ma'lumotni (summa, ulush, kontaktlar) egasining roziligisiz uchinchi shaxslarga berish;", "Platformaning ishlashiga xalaqit beradigan yoki uning himoyasini aylanib o'tishga urinadigan harakatlar."] },
    { h: '5. Kontent', p: ["Siz joylashtirgan ma'lumot (tavsiflar, logotiplar, raqamlar) uchun o'zingiz javobgarsiz. Bu ma'lumotni Platformada ko'rsatish uchun Investage'ga uni ishlatish huquqini berasiz.", "Platformadagi «Namuna» belgisi bilan ko'rsatilgan startap va investorlar platforma qanday ishlashini ko'rsatish uchun to'qilgan va haqiqiy shaxslar emas."] },
    { h: '6. Javobgarlikni cheklash', p: ["Investitsiya qarorlari va ular bilan bog'liq xatarlar to'liq foydalanuvchining zimmasida. Investage startaplar yoki investorlar tomonidan berilgan ma'lumotning to'g'riligi hamda tomonlar o'rtasidagi kelishuvlar natijasi uchun javobgar emas.", "Platforma «boricha» taqdim etiladi; uzluksiz va xatosiz ishlashi kafolatlanmaydi."] },
    { h: "7. Hisobni to'xtatish va o'chirish", p: ["Siz istalgan vaqtda hisobingizni Sozlamalar bo'limida o'chirishingiz mumkin. Ushbu shartlar buzilganda Investage hisobni cheklash yoki o'chirish huquqiga ega."] },
    { h: "8. O'zgartirishlar va aloqa", p: ["Shartlar vaqti-vaqti bilan yangilanishi mumkin; yangi tahrir shu sahifada e'lon qilinadi. Savollar bo'yicha «Yordam va fikr» sahifasi orqali murojaat qiling." + MAILTO, `Platformani yuritadi: ${OPERATOR.uz}.`, "Ushbu shartlarga O'zbekiston Respublikasi qonunchiligi qo'llaniladi."] },
  ],
  ru: [
    { h: '1. Общие положения', p: ['Investage (далее — «Платформа») — онлайн-сервис, который знакомит стартапы и инвесторов друг с другом. Используя Платформу или регистрируясь на ней, вы соглашаетесь с настоящими условиями.', 'Если вы не согласны с условиями, не пользуйтесь Платформой.'] },
    { h: '2. Аккаунт и регистрация', p: ['При регистрации необходимо указывать достоверные и актуальные данные. Пользоваться Платформой могут лица, достигшие 18 лет.', 'У каждого аккаунта одна роль: стартап или инвестор. Вы отвечаете за безопасность своего аккаунта и пароля.'] },
    { h: '3. Что делает Платформа и чего не делает', p: ['Платформа позволяет стартапам представить себя, а инвесторам — находить их и отправлять запросы на доступ к закрытым данным. Закрытые данные открываются только инвестору, которому стартап дал разрешение.', 'Investage не является финансовым посредником, брокером или инвестиционным консультантом. Платформа не принимает платежи и не переводит деньги: все договорённости и расчёты осуществляются напрямую между стартапом и инвестором.', 'Оценка Investage и отметка «Подтверждён» не являются инвестиционной рекомендацией или гарантией и предоставляются только как дополнительная информация.'] },
    { h: '4. Обязанности пользователя', p: ['Запрещается:'], list: ['размещать ложную или вводящую в заблуждение информацию;', 'мошенничество, спам или преследование других пользователей;', 'передавать открытые вам закрытые данные (сумму, долю, контакты) третьим лицам без согласия владельца;', 'действия, нарушающие работу Платформы или направленные на обход её защиты.'] },
    { h: '5. Контент', p: ['Вы отвечаете за размещённые вами данные (описания, логотипы, цифры) и предоставляете Investage право использовать их для отображения на Платформе.', 'Стартапы и инвесторы с отметкой «Пример» придуманы, чтобы показать работу Платформы, и не являются реальными лицами.'] },
    { h: '6. Ограничение ответственности', p: ['Инвестиционные решения и связанные с ними риски полностью лежат на пользователе. Investage не отвечает за достоверность данных, предоставленных стартапами или инвесторами, и за результат договорённостей между сторонами.', 'Платформа предоставляется «как есть»; бесперебойная и безошибочная работа не гарантируется.'] },
    { h: '7. Приостановка и удаление аккаунта', p: ['Вы можете удалить аккаунт в любой момент в разделе «Настройки». При нарушении условий Investage вправе ограничить или удалить аккаунт.'] },
    { h: '8. Изменения и связь', p: ['Условия могут обновляться; новая редакция публикуется на этой странице. По вопросам обращайтесь через страницу «Помощь и отзывы».' + MAILTO_RU, `Платформу ведёт: ${OPERATOR.ru}.`, 'К настоящим условиям применяется законодательство Республики Узбекистан.'] },
  ],
  en: [
    { h: '1. General', p: ['Investage (the “Platform”) is an online service that introduces startups and investors to each other. By using or registering on the Platform you agree to these terms.', 'If you do not agree with the terms, do not use the Platform.'] },
    { h: '2. Account and registration', p: ['You must provide accurate and up-to-date information when registering. The Platform is for persons aged 18 and over.', 'Each account has one role: startup or investor. You are responsible for keeping your account and password secure.'] },
    { h: '3. What the Platform does and does not do', p: ['The Platform lets startups present themselves and lets investors find them and send requests for access to closed details. Closed details open only to an investor the startup has approved.', 'Investage is not a financial intermediary, broker or investment adviser. The Platform does not accept payments or transfer money: all agreements and settlements are made directly between the startup and the investor.', 'The Investage score and the “Verified” mark are not investment advice or a guarantee; they are provided as additional information only.'] },
    { h: '4. User obligations', p: ['The following are prohibited:'], list: ['posting false or misleading information;', 'fraud, spam or harassing other users;', 'sharing closed details opened to you (amount, equity, contacts) with third parties without the owner’s consent;', 'actions that disrupt the Platform or attempt to bypass its protection.'] },
    { h: '5. Content', p: ['You are responsible for the information you post (descriptions, logos, figures) and grant Investage the right to use it to display it on the Platform.', 'Startups and investors marked “Sample” are made up to show how the Platform works and are not real persons.'] },
    { h: '6. Limitation of liability', p: ['Investment decisions and their risks rest entirely with the user. Investage is not responsible for the accuracy of information provided by startups or investors, or for the outcome of agreements between the parties.', 'The Platform is provided “as is”; uninterrupted and error-free operation is not guaranteed.'] },
    { h: '7. Suspension and deletion', p: ['You can delete your account at any time in Settings. If these terms are violated, Investage may restrict or delete the account.'] },
    { h: '8. Changes and contact', p: ['The terms may be updated; the new version is published on this page. For questions, use the “Help & feedback” page.' + MAILTO_EN, `The Platform is operated by: ${OPERATOR.en}.`, 'These terms are governed by the laws of the Republic of Uzbekistan.'] },
  ],
};

export const PRIVACY = {
  uz: [
    { h: "1. Qanday ma'lumot yig'iladi", p: ['Platforma quyidagi ma\'lumotlarni saqlaydi:'], list: ["hisob ma'lumotlari: ism, email, rol (startap yoki investor), parol (shifrlangan holda);", "profil ma'lumotlari: kompaniya, shahar, qiziqishlar, tavsif, investor sozlamalari, kontaktlar;", "startap ma'lumotlari: ochiq tanishtiruv, yopiq ma'lumot (summa, ulush, jamoa, kontaktlar), logotip;", "faoliyat: kirish so'rovlari, ruxsatlar, saqlangan startaplar, «Yordam va fikr» orqali yuborilgan murojaatlar;", "texnik cookie fayllar: kirish sessiyasi, tanlangan til va rang rejimi."] },
    { h: '2. Nima uchun ishlatiladi', p: ["Ma'lumotlar faqat hisobingizni yuritish, Platforma funksiyalarini ta'minlash (so'rovlar, ruxsatlar, bildirishnomalar), xavfsizlik va murojaatlaringizga javob berish uchun ishlatiladi. Ma'lumotlar sotilmaydi va reklama maqsadida uchinchi shaxslarga berilmaydi."] },
    { h: "3. Ma'lumotni kim ko'radi", list: ["startapning ochiq tanishtiruvi — barcha tashrif buyuruvchilar;", "startapning yopiq ma'lumoti — faqat startap ruxsat bergan investor;", "investor profili — investor o'zi ochiq qilgan bo'lsa ro'yxatdan o'tgan foydalanuvchilar, aks holda faqat u so'rov yuborgan startaplar;", "kontaktlar — faqat investor ruxsati bilan yoki u so'rov yuborgan startaplarga;", "Investage jamoasi — Platformani yuritish va murojaatlarga javob berish uchun."], p: [] },
    { h: '4. Xizmat ko\'rsatuvchilar va saqlash joyi', p: ["Platforma ishonchli xizmatlardan foydalanadi: Supabase (ma'lumotlar bazasi va fayllar, serverlar Germaniyada, Frankfurt), Vercel (sayt hostingi) va Telegram (murojaatlar haqida jamoaga xabar berish). Bu xizmatlar ma'lumotni faqat Platformani ishlatish uchun qayta ishlaydi."] },
    { h: '5. Cookie fayllar', p: ["Faqat zarur cookie fayllar ishlatiladi: kirish sessiyasi, til va rang rejimi. Reklama yoki kuzatuv cookie fayllari ishlatilmaydi."] },
    { h: '6. Sizning huquqlaringiz', p: ["Siz o'z ma'lumotlaringizni ko'rish va profil sahifasida tuzatish, kontaktlar va profil ko'rinishini boshqarish, hamda hisobingizni Sozlamalar bo'limida butunlay o'chirish huquqiga egasiz. Boshqa so'rovlar uchun «Yordam va fikr» sahifasi orqali murojaat qiling."] },
    { h: '7. Saqlash muddati', p: ["Ma'lumotlar hisobingiz o'chirilgunga qadar saqlanadi. Hisob o'chirilganda profil, startap ma'lumotlari, so'rovlar va saqlashlar o'chiriladi; yuborilgan murojaatlar esa hisob bilan bog'lanmagan holda qoladi."] },
    { h: '8. Xavfsizlik', p: ["Ulanish shifrlangan (HTTPS), parollar shifrlangan holda saqlanadi, kim qaysi ma'lumotni ko'rishi esa bevosita bazada tekshiriladi. Shunga qaramay, internetda 100% xavfsizlikni hech kim kafolatlay olmaydi."] },
    { h: "9. O'zgarishlar", p: ["Siyosat yangilanishi mumkin; yangi tahrir shu sahifada e'lon qilinadi. Platforma 18 yoshdan kichik shaxslar uchun mo'ljallanmagan."] },
  ],
  ru: [
    { h: '1. Какие данные собираются', p: ['Платформа хранит следующие данные:'], list: ['данные аккаунта: имя, email, роль (стартап или инвестор), пароль (в зашифрованном виде);', 'данные профиля: компания, город, интересы, описание, настройки инвестора, контакты;', 'данные стартапа: открытое описание, закрытые данные (сумма, доля, команда, контакты), логотип;', 'активность: запросы на доступ, разрешения, сохранённые стартапы, обращения через «Помощь и отзывы»;', 'технические cookie: сессия входа, выбранный язык и тема.'] },
    { h: '2. Для чего используются', p: ['Данные используются только для ведения вашего аккаунта, работы функций Платформы (запросы, разрешения, уведомления), безопасности и ответов на ваши обращения. Данные не продаются и не передаются третьим лицам в рекламных целях.'] },
    { h: '3. Кто видит данные', list: ['открытое описание стартапа — все посетители;', 'закрытые данные стартапа — только инвестор, которому стартап дал разрешение;', 'профиль инвестора — зарегистрированные пользователи, если инвестор открыл профиль, иначе только стартапы, которым он отправил запрос;', 'контакты — только с разрешения инвестора или стартапам, которым он отправил запрос;', 'команда Investage — для работы Платформы и ответов на обращения.'], p: [] },
    { h: '4. Поставщики услуг и место хранения', p: ['Платформа использует надёжные сервисы: Supabase (база данных и файлы, серверы в Германии, Франкфурт), Vercel (хостинг сайта) и Telegram (уведомления команде об обращениях). Эти сервисы обрабатывают данные только для работы Платформы.'] },
    { h: '5. Cookie', p: ['Используются только необходимые cookie: сессия входа, язык и тема. Рекламные и отслеживающие cookie не используются.'] },
    { h: '6. Ваши права', p: ['Вы можете просматривать и исправлять свои данные на странице профиля, управлять видимостью профиля и контактов, а также полностью удалить аккаунт в разделе «Настройки». По другим вопросам обращайтесь через страницу «Помощь и отзывы».'] },
    { h: '7. Срок хранения', p: ['Данные хранятся до удаления аккаунта. При удалении аккаунта удаляются профиль, данные стартапа, запросы и сохранения; отправленные обращения остаются без привязки к аккаунту.'] },
    { h: '8. Безопасность', p: ['Соединение зашифровано (HTTPS), пароли хранятся в зашифрованном виде, а права доступа к данным проверяются непосредственно в базе. Тем не менее никто не может гарантировать 100% безопасность в интернете.'] },
    { h: '9. Изменения', p: ['Политика может обновляться; новая редакция публикуется на этой странице. Платформа не предназначена для лиц младше 18 лет.'] },
  ],
  en: [
    { h: '1. What data is collected', p: ['The Platform stores the following data:'], list: ['account data: name, email, role (startup or investor), password (encrypted);', 'profile data: company, city, interests, bio, investor settings, contacts;', 'startup data: public introduction, closed details (amount, equity, team, contacts), logo;', 'activity: access requests, approvals, saved startups, messages sent via “Help & feedback”;', 'technical cookies: login session, chosen language and theme.'] },
    { h: '2. Why it is used', p: ['Data is used only to run your account, provide Platform features (requests, approvals, notifications), keep it secure and respond to your messages. Data is not sold or shared with third parties for advertising.'] },
    { h: '3. Who can see the data', list: ['a startup’s public introduction — all visitors;', 'a startup’s closed details — only an investor the startup has approved;', 'an investor profile — registered users if the investor made it public, otherwise only startups the investor sent a request to;', 'contacts — only with the investor’s permission or to startups the investor sent a request to;', 'the Investage team — to run the Platform and answer messages.'], p: [] },
    { h: '4. Service providers and storage location', p: ['The Platform uses reliable services: Supabase (database and files, servers in Frankfurt, Germany), Vercel (website hosting) and Telegram (notifying the team about messages). These services process data only to run the Platform.'] },
    { h: '5. Cookies', p: ['Only necessary cookies are used: login session, language and theme. No advertising or tracking cookies are used.'] },
    { h: '6. Your rights', p: ['You can view and correct your data on your profile page, control the visibility of your profile and contacts, and fully delete your account in Settings. For other requests, use the “Help & feedback” page.'] },
    { h: '7. Retention', p: ['Data is kept until your account is deleted. Deleting the account removes the profile, startup data, requests and saved items; messages you sent remain without a link to the account.'] },
    { h: '8. Security', p: ['The connection is encrypted (HTTPS), passwords are stored encrypted, and access rights are checked directly in the database. Even so, nobody can guarantee 100% security on the internet.'] },
    { h: '9. Changes', p: ['This policy may be updated; the new version is published on this page. The Platform is not intended for persons under 18.'] },
  ],
};
